# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - rehab_arm_moveit_controller

  rehab_arm_moveit_controller:
    type: FollowJointTrajectory
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
    action_ns: follow_joint_trajectory
    default: true